# General Settings
SR_type: 'SISR' # [SISR, MISR] # dont forget to also set the sen2_amount
bands: 3

# Data Settings
Data:
  # Loader Settings
  train_batch_size: 12 #12
  val_batch_size: 8
  num_workers: 6
  prefetch_factor: 4 #8 #2
  data_type: "8bit" # ["8bit", "SEN2"]

  # Detailed Dataset Setttings
  dataset_type: 'GE' # ['cv', 'SPOT6','SEN2NAIP','GE']
  data_dir: None # ['data/openImages/',''E:/thesis_paper/data/',None]
  sen2_amount: 1
  spectral_matching: None # ['histogram', None]
  return_type: None # [interpolated_matched, None]

  # Test Dataset
  test_dataset: 'sen2_test' # ['sen2_test',None]


# Model, Loss, Training  Settings
Model:
  load_checkpoint: True
  ckpt_path: "logs/2023_SRGAN_4band/2024-06-06_11-36-01/epoch=126-step=247904.ckpt"
  load_fusion_checkpoint: False
  fusion_ckpt_path: 'logs/curated_ckpts/pretrained_Fusion.ckpt'
Warmup:
  fusion: # train fusion in isolation previously.
    enable: False
    epochs: 1
    lr: 1e-4

Generator:
  large_kernel_size: 9
  small_kernel_size: 3
  n_channels: 64
  n_blocks: 16
  scaling_factor: 4

Discriminator:
  kernel_size: 3
  n_channels: 64
  n_blocks: 8
  fc_size: 1024

TruncatedVGG:
  i: 5
  j: 4

Optimizers:
  optim_g_lr: 1e-5
  optim_d_lr: 1e-5

Schedulers:
  metric: 'val/L1' # 'val/L1' - val only available in epoch mode
  interval: 'epoch' # ['step', 'epoch']
  patience_g: 15
  patience_d: 15
  factor_g: 0.25
  factor_d: 0.25
  verbose: True

Losses:
  adv_loss_beta:  1e-3

Logging:
  num_val_images: 5 # how many images logged per val cycle